services:
  mysql:
    image: 'mysql:latest'
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_USER=${DATABASE_USERNAME}
    ports:
      - '3307:3306'
